; Generated by AutoGUI 2.5.8
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui +Owner
Gui Font, s12
Gui Color, 303030
Menu HelpMenu, Add, Open Readme, readmeL
Menu MenuBar, Add, Help, :HelpMenu
Gui Menu, MenuBar

Gui Add, Tab3, cwhite x-1 y-3 w981 h619 +Buttons, Quick Access|Install  ;creates multiple tabs
Gui Tab, Install ; now under Install tab
Gui Font, s10
Gui Add, Button, x0 y32 w110 h23, Essential Install
Gui Add, Text, cwhite x+20 y32, Essential Install installs these Programms
Gui Font, s13 Bold
Gui Add, Text, cWhite x0 y80 w162 h30, Selective Install

Gui Font, s10
Gui Add, Text, c38a2ff x0 y100 , Image
Gui Font, 
Gui add, Button, x95 y100 gcanva, Canva
Gui add, Button, x+1 gsharex, ShareX

Gui Font, s10 Bold
Gui Add, Text, c38a2ff x0 y+10 , Tools
Gui Font,
Gui, Add, Button, x+55 g7zip, 7zip
Gui, Add, Button, x+1 gnotepads, Notepads
Gui, Add, Button, x+1 gventoy, Ventoy
Gui, Add, Button, x+1 geverything, Everything
Gui, Add, Button, x+1 gpandoc, Pandoc
Gui, Add, Button, x+1 gautohotkey, Autohotkey
Gui, Add, Button, x+1 gccleaner, CCleaner
Gui, Add, Button, x+1 gpowertoys, Powertoys
Gui, Add, Button, x+1 grevo, RevoUninstaller
Gui, Add, Button, x95 y+10 gwinaerotweaker, Winaerotweaker

Gui Font, s10 Bold
Gui Add, Text, c38a2ff x0 y+10 , Customization
Gui Font,
Gui, Add, Button, x+1 gtaskbarx, TaskbarX
Gui, Add, Button, x+1 gqttabbar, qttabbar

Gui Font, s10 Bold
Gui Add, Text, c38a2ff x0 y+10 , Internet
Gui Font,
Gui, Add, Button, x+45 gchrome, Chrome
Gui, Add, Button, x+1 gfdm, FDM
Gui, Add, Button, x+1 gmega, Mega

Gui Font, s10 Bold
Gui Add, Text, c38a2ff x0 y+10 , Others
Gui Font,
Gui, Add, Button, x+50 gobsidian, Obsidian
Gui, Add, Button, x+1 gdrawboard, Drawboard
Gui, Add, Button, x+1 gxodo, Xodo

Gui Tab, Quick Access ; now under Quick Acces Tab
Gui Add, CheckBox, x192 y98 w120 h23, CheckBox





Gui Tab ; shows the tab in gui

Gui Show, w622 h357, AmazeX Utility
Return

readmeL:
Run,  https://github.com/elitefantasy/AmazeX-Utility#amaze-utility
Return

GuiEscape:
GuiClose:
ExitApp

; Button Labels
canva:
run, *runas cmd.exe /k echo installing program please wait && winget install Canva.Canva && pause && exit
Return

sharex:
run, *runas cmd.exe /k echo installing program please wait... && choco install sharex && pause && exit
Return

7zip:
run, *runas cmd.exe /k echo installing program please wait... && choco install 7zip && pause && exit
Return

notepads:
run, *runas cmd.exe /k echo installing program please wait... && winget install JackieLiu.NotepadsApp && pause && exit
Return

ventoy:
run, *runas cmd.exe /k echo installing program please wait... && choco install ventoy && pause && exit
Return

everything:
run, *runas cmd.exe /k echo installing program please wait... && choco install everything && pause && exit
Return

pandoc:
run, *runas cmd.exe /k echo installing program please wait... && choco install pandoc && pause && exit
Return

autohotkey:
run, *runas cmd.exe /k echo installing program please wait... && choco install autohotkey && pause && exit
Return

ccleaner:
run, *runas cmd.exe /k echo installing program please wait... && choco install ccleaner && pause && exit
Return

powertoys:
run, *runas cmd.exe /k echo installing program please wait... && choco install powertoys && pause && exit
Return

revo:
run, *runas cmd.exe /k echo installing program please wait... && choco install revo-uninstaller && pause && exit
Return

winaerotweaker:
run, *runas cmd.exe /k echo installing program please wait... && choco install winaero-tweaker && pause && exit
Return

taskbarx:
run, *runas cmd.exe /k echo installing program please wait... && winget install 9PCMZ6BXK8GH && pause && exit
Return

qttabbar:
run, *runas cmd.exe /k echo installing program please wait... && choco install qttabbar && pause && exit
Return

chrome:
run, *runas cmd.exe /k echo installing program please wait... && choco install googlechrome && pause && exit
Return

fdm:
run, *runas cmd.exe /k echo installing program please wait... && choco install freedownloadmanager && pause && exit
Return

mega:
run, *runas cmd.exe /k echo installing program please wait... && choco install megasync && pause && exit
Return

obsidian:
run, *runas cmd.exe /k echo installing program please wait... && choco install obsidian && pause && exit
Return

drawboard:
run, *runas cmd.exe /k echo installing program please wait... && winget install 9WZDNCRFHWQT && pause && exit
Return

xodo:
run, *runas cmd.exe /k echo installing program please wait... && winget install 9WZDNCRDJXP4 && pause && exit
Return